services:
  - type: worker
    name: telegram-bot
    runtime: docker
    plan: starter  # Изменено на starter, так как free-воркеры через yaml не поддерживаются
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TG_BOT_TOKEN
        sync: false
      - key: BOT_MODERATORS
        sync: false
      - key: JAVA_OPTS
        value: "-Xmx256m -Xms128m"
    autoDeploy: true
